### ISSUE TITLE
Background issue with RetroPie 4.5.9

### ISSUE THREAD

**Issue by fsegouin** [KALEL1981/es-theme-Super-Retroboy#2]
Just updated to RetroPie 4.5.9 and now it seems like the game information is in the background behind the actual theme overlay? Using latest release of the Super Retroboy theme.

![IMG_0861](https://user-images.githubusercontent.com/2843216/72167695-8c144780-33c3-11ea-9290-b252be94db80.jpg)

**Comment by KALEL1981** [comment]
I will look into this as soon as I can today. Thank you for the heads up
👍🏻

**Comment by KALEL1981** [comment]
I have updated the theme. Update to the newest version and let me know if the issue is resolved.

**Comment by fsegouin** [comment]
Can confirm 1f1aeb9 fixed it! Thanks @KALEL1981 :)
