### ISSUE TITLE
Request For Solarus System Support

### ISSUE THREAD

**Issue by Dark98** [KALEL1981/es-theme-Super-Retroboy#7]
Solarus Is 100% Usable With The GPi Case & The Only Setup It Requires It Setting The "Engine Exit" Button Combo (8+9 for the same as other systems)

**Comment by KALEL1981** [comment]
I’ll add it to the theme this week when I get a chance.

**Comment by Dark98** [comment]
Thank you :) added with 2d3ab64a9c4ee11547914911265d79cafe188775
